/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    CategoryFormModal: typeof import('./components/Categories/CategoryFormModal.vue')['default']
    ChipStatus: typeof import('./components/Shared/ChipStatus.vue')['default']
    ConfirmDialog: typeof import('./components/Shared/ConfirmDialog.vue')['default']
    ContainerDefault: typeof import('./components/ContainerDefault.vue')['default']
    MenuComponent: typeof import('./components/MenuComponent.vue')['default']
    MetricCard: typeof import('./components/Dashboard/MetricCard.vue')['default']
    ProductFormModal: typeof import('./components/Products/ProductFormModal.vue')['default']
    ProductTable: typeof import('./components/Products/ProductTable.vue')['default']
    QuickActionsCard: typeof import('./components/Dashboard/QuickActionsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TotalCard: typeof import('./components/Dashboard/MetricCard.vue')['default']
  }
}
